language: cpp

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

compiler:
  - gcc

script:
  - make -e realclean &&
    make -e PEDANTIC=1 -j

  - cd ${TRAVIS_BUILD_DIR}/samples/copy &&
    make -e realclean &&
    make -e PEDANTIC=1 &&
    ./copy.sh i 2 2 512

  - cd ${TRAVIS_BUILD_DIR}/samples/entropy &&
    make -e realclean &&
    make -e PEDANTIC=1 &&
    ./entropy.sh -test

  - cd ${TRAVIS_BUILD_DIR}/samples/multi-dgemm &&
    make -e realclean &&
    make -e PEDANTIC=1

  - cd ${TRAVIS_BUILD_DIR}/samples/test &&
    make -e realclean &&
    make -e PEDANTIC=1
