language: cpp

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

compiler:
  - gcc

script:
  - make -e realclean &&
    make -e PEDANTIC=1 -j

  - cd samples/copy &&
    make -e realclean &&
    make -e PEDANTIC=1 &&
    ./copy.sh &&
    cd ../..

  - cd samples/entropy &&
    make -e realclean &&
    make -e PEDANTIC=1 &&
    ./entropy.sh -test &&
    cd ../..

  - cd samples/multi-dgemm &&
    make -e realclean &&
    make -e PEDANTIC=1 &&
    cd ../..

  - cd samples/test &&
    make -e realclean &&
    make -e PEDANTIC=1 &&
    cd ../..
