language: cpp

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev

compiler:
  - gcc

script:
  - make -e realclean &&
    make -e -j
  - cd samples/copy &&
    make -e
  - cd samples/entropy &&
    make -e
  - cd samples/multi-dgemm &&
    make -e
  - cd samples/test &&
    make -e
